[2025-06-05T15:14:14.718+0700] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: color_log_test.generate_test_logs manual__2025-06-05T08:14:10.185551+00:00 [queued]>
[2025-06-05T15:14:14.720+0700] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: color_log_test.generate_test_logs manual__2025-06-05T08:14:10.185551+00:00 [queued]>
[2025-06-05T15:14:14.721+0700] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2025-06-05T15:14:14.721+0700] {taskinstance.py:1363} INFO - Starting attempt 1 of 2
[2025-06-05T15:14:14.721+0700] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2025-06-05T15:14:14.725+0700] {taskinstance.py:1383} INFO - Executing <Task(PythonOperator): generate_test_logs> on 2025-06-05 08:14:10.185551+00:00
[2025-06-05T15:14:14.727+0700] {standard_task_runner.py:55} INFO - Started process 97275 to run task
[2025-06-05T15:14:14.730+0700] {standard_task_runner.py:82} INFO - Running: ['airflow', 'tasks', 'run', 'color_log_test', 'generate_test_logs', 'manual__2025-06-05T08:14:10.185551+00:00', '--job-id', '5', '--raw', '--subdir', 'DAGS_FOLDER/color_log_test_dag.py', '--cfg-path', '/var/folders/lz/x0br3qp171708_6wp9t3swxcgzm1g0/T/tmp6wi8jvdn']
[2025-06-05T15:14:14.732+0700] {standard_task_runner.py:83} INFO - Job 5: Subtask generate_test_logs
[2025-06-05T15:14:14.766+0700] {task_command.py:376} INFO - Running <TaskInstance: color_log_test.generate_test_logs manual__2025-06-05T08:14:10.185551+00:00 [running]> on host r6mwyf6lkg.local
[2025-06-05T15:14:14.829+0700] {taskinstance.py:1590} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=color_log_test
AIRFLOW_CTX_TASK_ID=generate_test_logs
AIRFLOW_CTX_EXECUTION_DATE=2025-06-05T08:14:10.185551+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2025-06-05T08:14:10.185551+00:00
[2025-06-05T15:14:14.831+0700] {color_log_test_dag.py:27} INFO - This is a standard INFO log message
[2025-06-05T15:14:14.832+0700] {color_log_test_dag.py:31} WARNING - This is a WARNING message that should appear in yellow
[2025-06-05T15:14:14.834+0700] {color_log_test_dag.py:32} WARNING - Another WARNING: This task might be slow
[2025-06-05T15:14:14.834+0700] {color_log_test_dag.py:35} ERROR - This is an ERROR message that should appear in bold red
[2025-06-05T15:14:14.835+0700] {color_log_test_dag.py:36} ERROR - Another ERROR: Something went wrong with parameter X
[2025-06-05T15:14:14.837+0700] {color_log_test_dag.py:39} INFO - This message contains the word 'error' and should be partially highlighted
[2025-06-05T15:14:14.838+0700] {color_log_test_dag.py:42} INFO - This message mentions an exception and should also be highlighted
[2025-06-05T15:14:14.839+0700] {color_log_test_dag.py:49} ERROR - Caught an exception: division by zero
[2025-06-05T15:14:14.841+0700] {color_log_test_dag.py:50} ERROR - Traceback (most recent call last):
  File "/Users/phuongcbnguyen/Projects/airflow-project/airflow_home/dags/color_log_test_dag.py", line 47, in generate_test_logs
    result = 1 / 0
             ~~^~~
ZeroDivisionError: division by zero

[2025-06-05T15:14:14.842+0700] {python.py:177} INFO - Done. Returned value was: Log test completed
[2025-06-05T15:14:14.850+0700] {taskinstance.py:1401} INFO - Marking task as SUCCESS. dag_id=color_log_test, task_id=generate_test_logs, execution_date=20250605T081410, start_date=20250605T081414, end_date=20250605T081414
[2025-06-05T15:14:14.878+0700] {local_task_job.py:159} INFO - Task exited with return code 0
[2025-06-05T15:14:14.887+0700] {taskinstance.py:2623} INFO - 1 downstream tasks scheduled from follow-on schedule check
